### ISSUE TITLE
 Modules docs are not generated

### ISSUE THREAD

**Issue by thrix** [gluetool/gluetool#15]
modules.rst is not generated, needs investigation and fix

**Comment by thrix** [comment]
build logs: https://readthedocs.org/projects/gluetool/builds/

**Comment by thrix** [comment]
Will try to look @ this

**Comment by thrix** [comment]
Might not be related, but there are some tracebacks during the generation:
```
/home/docs/checkouts/readthedocs.org/user_builds/gluetool/checkouts/latest/docs/source/gluetool.pylint.rst:15: WARNING: autodoc: failed to import module u'gluetool.pylint'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/gluetool/envs/latest/lib/python2.7/site-packages/Sphinx-1.5.2-py2.7.egg/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gluetool/envs/latest/local/lib/python2.7/site-packages/gluetool-1.1.dev12+g185a5ae-py2.7.egg/gluetool/pylint/__init__.py", line 5, in <module>
    from .shared_defined import register_checkers as register_shared_defined
  File "/home/docs/checkouts/readthedocs.org/user_builds/gluetool/envs/latest/local/lib/python2.7/site-packages/gluetool-1.1.dev12+g185a5ae-py2.7.egg/gluetool/pylint/shared_defined.py", line 5, in <module>
    import astroid
ImportError: No module named astroid
/home/docs/checkouts/readthedocs.org/user_builds/gluetool/checkouts/latest/docs/source/gluetool.pylint.shared_defined.rst:4: WARNING: autodoc: failed to import module u'gluetool.pylint.shared_defined'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/gluetool/envs/latest/lib/python2.7/site-packages/Sphinx-1.5.2-py2.7.egg/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gluetool/envs/latest/local/lib/python2.7/site-packages/gluetool-1.1.dev12+g185a5ae-py2.7.egg/gluetool/pylint/__init__.py", line 5, in <module>
    from .shared_defined import register_checkers as register_shared_defined
  File "/home/docs/checkouts/readthedocs.org/user_builds/gluetool/envs/latest/local/lib/python2.7/site-packages/gluetool-1.1.dev12+g185a5ae-py2.7.egg/gluetool/pylint/shared_defined.py", line 5, in <module>
    import astroid
ImportError: No module named astroid
/home/docs/checkouts/readthedocs.org/us
```
